# FEATURE ENGINEERING
refers to transformation of cleaned raw data into features that are suitable for modeling.feature engineering can be divided  into three:
    
    1.FEATURE EXTRACTION
    
    
    2.FEATURE TRANSFORMATION
    
    
    3.FEATURE SELECTION
    
    
    


# steps when creating a model
data collection--> data cleaning-->data visualization-->feature engineering--->ml model training

# 1.FEATURE TRANSFORMATION
This involves changing the feature from one form to another since the cmpoter only understand numeric values but for categorical values we have to transform them  to numeric e.g 0's and 1's and so as to improve the accuracy of the model.
transformation can be done in two ways that are

a) feature encoding > its where we convert the categorical variables to   numerical values

b) Feature scaling >where we make the features to be in the same  scale/range,there are two ways of scaling the data which includes.

   i) NORMALIZATION 
   
   ii) STANDARDIZATION 
    


# 2.FEATURE EXTRACTION
Feature extraction is a method for creating a new and smaller set of features that captures most of the useful information of raw data.these raw data can be where we can extract the features ca be text,images,web data etc.

-we extract useful features from existing clean raw data

# 3. FEATURE SELECTION

- it is where we select the best features which are most relevant to our machine model

- Choosing a subset of the original pool of features.

# FEATURE TRAOSFORMATION

# A)   ENCODING

Machine learning cannot work with the categorical variables since its biased to the language that we use. we can generally divide categorical variables  into three types

* binary  features > yes/no, true or false 


* ordinal features > there are specific ordered groups e.g (education level) phd can be ranked as 2, mastters can be ranked as 1, degree can be ranked as 0 , also (income level) as low income, middle income,high income


* norminal features >there are unordered  groups  that is there are no order to be followed e.g gender, age, 

#  i)  Encoding  of binary features

In [1]:
import pandas as pd
import numpy as np


In [2]:
#import the dataset
df=pd.read_csv("breast-cancer.csv")

In [4]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [5]:
df.tail()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
564  926424         M        21.56         22.39          142.00     1479.0   
565  926682         M        20.13         28.25          131.20     1261.0   
566  926954         M        16.60         28.08          108.30      858.1   
567  927241         M        20.60         29.33          140.10     1265.0   
568   92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
564                0.2216          0.2060                  0.07115  
565                0.1628          0.2572                  0.06637  
566                0.1418          0.2218                  0.07820  
567                0.2650          0.4087                  0.12400  
568                0.0000          0.2871                  0.07039  

[5 rows x 32 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [9]:
#Encoding the diagnosis column where it has binary features either maligant or benign 
y=df["diagnosis"].apply(lambda y_value:0 if y_value == "B" else 1)


In [11]:
print(y.to_string())

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     0
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
30     1
31     1
32     1
33     1
34     1
35     1
36     1
37     0
38     1
39     1
40     1
41     1
42     1
43     1
44     1
45     1
46     0
47     1
48     0
49     0
50     0
51     0
52     0
53     1
54     1
55     0
56     1
57     1
58     0
59     0
60     0
61     0
62     1
63     0
64     1
65     1
66     0
67     0
68     0
69     0
70     1
71     0
72     1
73     1
74     0
75     1
76     0
77     1
78     1
79     0
80     0
81     0
82     1
83     1
84     0
85     1
86     1
87     1
88     0
89     0
90     0
91     1
92     0
93     0
94     1
95     1
96     0
97     0
98     0
99     1
100    1
101    0
102    0
103    0
104    0
105    1
106    0
107    0
108    1
109    0
110    0
1

#  ii)  encoding of ordinal features
ordinal features there are those features can be  ordered/ranked. to transform this features we use two methods that assign integer based on alphabetic ordering.

* OrdinalEncorder

* LabelEncoder

In [12]:
# creating the dataframe
mydataframe={"education level":["bachelor","phd","master","bachelor","phd","master"]}
x=pd.DataFrame(mydataframe)
x

education level
0        bachelor
1             phd
2          master
3        bachelor
4             phd
5          master

In [14]:
# import the library
from sklearn.preprocessing import OrdinalEncoder

# >OrdinalEncoder

In [15]:
y=OrdinalEncoder()
y.fit_transform(x.values)

array([[0.],
       [2.],
       [1.],
       [0.],
       [2.],
       [1.]])

In [16]:
y.categories_

[array(['bachelor', 'master', 'phd'], dtype=object)]

In [153]:
#maintaining the order in terms of alphabetical order

# >> LabelEncoder
it is a technique where each label is assigned a unique integer based on alphabetical ordering

In [17]:
#import the library
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()
le.fit_transform(x.values)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 2, 1, 0, 2, 1])

# comparison between labelencoder and ordinalencoder

* ordinalencoder is used in encoding features(2D) while labelencoder is used in converting target variables(1D)


* OrdinalEncoder is for 2D data shape while labelEncoder is for 1D array


# iii) Encoding of nominal features
norminal features are those features that do not have any ordering e.g gender,city,location etc.

in encoding norminal features we use technique known as one_hot_encoding




# One_hot_encoding

In [19]:
#load dataset
data=pd.read_csv("IRIS.csv")

In [20]:
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [21]:
data.tail()

sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [22]:
data["species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [23]:
#import the library
from sklearn.preprocessing import OneHotEncoder

In [24]:
enc=OneHotEncoder()
dx=enc.fit_transform(data.species.values.reshape(-1,1)).toarray()
dx


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

# B.feature scalling
it is one of the important preprocessing method required for standardization/normalization of input data.

why do we have to scale the data?

we scale the data to ensure that our model is not biased by considering the column with higher range of values and treat that column as  important than others/give it a higher prioty.therefore scaling tries to  makes our features to be in the same range.



# feature scaling techniques
we use the following techniques when scaling the data

a) standardization

 - scaling data to fit a standard normal distribution by making the mean to 0 and standard deviation to 1
 

b) normalization

 - making all the features in the range of 0 to 1
 
 - it is also called min-max scaling

In [25]:
df=pd.read_csv("diabetes.csv")

In [26]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [27]:
df.shape

(768, 9)

In [30]:
#splitting the data
x=df.drop("Outcome",axis=1)
y=df["Outcome"]

In [31]:
print(x.shape)

(768, 8)


In [32]:
print(y.shape)

(768,)


In [33]:
#import the library for test train split
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

# normalization
we use  minmaxscaler

In [38]:
#importing the library for scaling
from sklearn.preprocessing import MinMaxScaler

In [43]:
scale=MinMaxScaler()
z=scale.fit_transform(x)
np.set_printoptions(precision=3)

In [44]:
print(z)

[[0.353 0.744 0.59  ... 0.501 0.234 0.483]
 [0.059 0.427 0.541 ... 0.396 0.117 0.167]
 [0.471 0.92  0.525 ... 0.347 0.254 0.183]
 ...
 [0.294 0.608 0.59  ... 0.39  0.071 0.15 ]
 [0.059 0.633 0.492 ... 0.449 0.116 0.433]
 [0.059 0.467 0.574 ... 0.453 0.101 0.033]]


# standardization
we use standardscaler

In [45]:
#import the library
from sklearn.preprocessing import StandardScaler

In [46]:
scale=StandardScaler()
z=scale.fit_transform(x)
np.set_printoptions(precision=3)

In [47]:
print(z)

[[ 0.64   0.848  0.15  ...  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161 ... -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 ... -1.103  0.604 -0.106]
 ...
 [ 0.343  0.003  0.15  ... -0.735 -0.685 -0.276]
 [-0.845  0.16  -0.471 ... -0.24  -0.371  1.171]
 [-0.845 -0.873  0.046 ... -0.202 -0.474 -0.871]]


# SUMMARY

Feature engineering

                    > feature transformation
         
                    >feature extraction
                    
                    >feature selection
                    
feature transformation

                       >encoding
                       
                       >scaling
                     
 Encoding
         
         >binary feature(yes/no)
         
         >ordinalfeatures(ordered)
         
               *ordinalencoder
               
               *labelencoder
         
         >nominal features(unordered)
                
                 *one_hot_encoding
                
 scaling
        
         >nornalization(minmaxscaler)
         
         >standardization(standardscaler)

# END
HAPPY LEARNING!

HAPPY CODING!
    